
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 08 18:58:35 GMT-03:00 2020
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int APLICACAO = 2;
  public static final int DECIMAL = 11;
  public static final int ATRIBUICAO = 7;
  public static final int INTEIRO = 9;
  public static final int TIPO_INTEIRO = 6;
  public static final int PTVG = 8;
  public static final int TIPO_CARACTER = 5;
  public static final int INICIOAPP = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FIMAPP = 4;
  public static final int VARIAVEL = 12;
  public static final int CHAR = 10;
}

